version: '3'
services:
  backend_1:
    build: ./
    restart : always
    ports:
      - "4001:4000"
    tty: true
    stdin_open: true
  backend_2:
    build: ./
    restart : always
    ports:
      - "4002:4000"
    tty: true
    stdin_open: true
  nginx:
    build: client/
    restart : always
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend_1
      - backend_2
    tty: true
    stdin_open: true
  